version: "3.9"

services:
  tsla-api:
    build: .
    container_name: tsla-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn api_tsla:app --host 0.0.0.0 --port 8000 --reload
